local t = require("spec.util.test_base")
local position = require("../src/position")

t.assert_eq("BTN", position.offset_long_to_short("Button"))
t.assert_eq("SB", position.offset_long_to_short("Small Blind"))
t.assert_eq("BB", position.offset_long_to_short("Big Blind"))
t.assert_eq("HJ", position.offset_long_to_short("Hijack"))
t.assert_eq("LJ", position.offset_long_to_short("Lojack"))
t.assert_eq("UTG", position.offset_long_to_short("Under the Gun"))
t.assert_eq("+1", position.offset_long_to_short("UTG+1"))
t.assert_eq("+2", position.offset_long_to_short("UTG+2"))
t.assert_eq("CO", position.offset_long_to_short("Cutoff"))

t.assert_eq("Button", position.offset_to_name(0, 2))
t.assert_eq("Big Blind", position.offset_to_name(1, 2))

t.assert_eq("Button", position.offset_to_name(0, 3))
t.assert_eq("Small Blind", position.offset_to_name(1, 3))
t.assert_eq("Big Blind", position.offset_to_name(2, 3))

t.assert_eq("Button", position.offset_to_name(0, 4))
t.assert_eq("Small Blind", position.offset_to_name(1, 4))
t.assert_eq("Big Blind", position.offset_to_name(2, 4))
t.assert_eq("Cutoff", position.offset_to_name(3, 4))

t.assert_eq("Button", position.offset_to_name(0, 5))
t.assert_eq("Small Blind", position.offset_to_name(1, 5))
t.assert_eq("Big Blind", position.offset_to_name(2, 5))
t.assert_eq("Under the Gun", position.offset_to_name(3, 5))
t.assert_eq("Cutoff", position.offset_to_name(4, 5))

t.assert_eq("Button", position.offset_to_name(0, 6))
t.assert_eq("Small Blind", position.offset_to_name(1, 6))
t.assert_eq("Big Blind", position.offset_to_name(2, 6))
t.assert_eq("Under the Gun", position.offset_to_name(3, 6))
t.assert_eq("Hijack", position.offset_to_name(4, 6))
t.assert_eq("Cutoff", position.offset_to_name(5, 6))

t.assert_eq("Button", position.offset_to_name(0, 7))
t.assert_eq("Small Blind", position.offset_to_name(1, 7))
t.assert_eq("Big Blind", position.offset_to_name(2, 7))
t.assert_eq("Under the Gun", position.offset_to_name(3, 7))
t.assert_eq("Lojack", position.offset_to_name(4, 7))
t.assert_eq("Hijack", position.offset_to_name(5, 7))
t.assert_eq("Cutoff", position.offset_to_name(6, 7))

t.assert_eq("Button", position.offset_to_name(0, 8))
t.assert_eq("Small Blind", position.offset_to_name(1, 8))
t.assert_eq("Big Blind", position.offset_to_name(2, 8))
t.assert_eq("Under the Gun", position.offset_to_name(3, 8))
t.assert_eq("UTG+1", position.offset_to_name(4, 8))
t.assert_eq("Lojack", position.offset_to_name(5, 8))
t.assert_eq("Hijack", position.offset_to_name(6, 8))
t.assert_eq("Cutoff", position.offset_to_name(7, 8))

t.assert_eq("Button", position.offset_to_name(0, 9))
t.assert_eq("Small Blind", position.offset_to_name(1, 9))
t.assert_eq("Big Blind", position.offset_to_name(2, 9))
t.assert_eq("Under the Gun", position.offset_to_name(3, 9))
t.assert_eq("UTG+1", position.offset_to_name(4, 9))
t.assert_eq("UTG+2", position.offset_to_name(5, 9))
t.assert_eq("Lojack", position.offset_to_name(6, 9))
t.assert_eq("Hijack", position.offset_to_name(7, 9))
t.assert_eq("Cutoff", position.offset_to_name(8, 9))
